[build]
command = "npm run build"
pages_build_output_dir = ".next"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"
entry-point = "."

[[build.upload]]
type = "Pages"
dir = ".next"
main = ".next/server/app/page.js"
include = [
  ".next/server/**/*",
  ".next/static/**/*",
  "public/**/*"
] 